apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: luftschmaus-dev
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: luftschmaus-database/POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: luftschmaus-database/POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: luftschmaus-database/POSTGRES_DB
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: luftschmaus-staging
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: luftschmaus-database/POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: luftschmaus-database/POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: luftschmaus-database/POSTGRES_DB
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: luftschmaus-production
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: luftschmaus-database/POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: luftschmaus-database/POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: luftschmaus-database/POSTGRES_DB
