apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: luftschmaus-dev
spec:
  provider:
    onepasswordSDK:
      vault: luftschmaus
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: luftschmaus-staging
spec:
  provider:
    onepasswordSDK:
      vault: luftschmaus
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: luftschmaus-production
spec:
  provider:
    onepasswordSDK:
      vault: luftschmaus
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
